/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include "mochi_common_components.h"

#include <mochi_core/contact/contact_utils.h>
#include <mochi_core/utils/dynamic_array.h>
#include <mochi_core/utils/span.h>

#include <algorithm>
#include <utility>

namespace mochi {

// Contact components and functions are templatized by kIsSync:
// - Async contact (kIsSync = false) is used for static colliders and applies contact forces only to
// the colliding actor.
// - Sync contact (kIsSync = true) is used for dynamic colliders and applies contact forces to both
// colliding and collider actors.

/**
 * @brief Stores a list of entities that might contact the actor during any iteration of the current
 * step. This list is generated by finding actors with overlapping @ref CConservativeStepBounds.
 * Templatized according to async or sync contact.
 */
template <bool kIsSync>
struct CConservativePotentialColliders : public DynamicArray<entt::entity> {};

/**
 * @brief Stores a list of entities that might contact the actor during the current iteration. This
 * list is generated by finding actors with overlapping @ref CBoundingVolume. Templatized according
 * to async or sync contact.
 */
template <bool kIsSync>
struct CPotentialColliders : public DynamicArray<entt::entity> {};

/** @brief Information of a collision pair with a collider actor. */
struct ActiveCollision {
  entt::entity colliderEntity = {}; // Entity of the corresponding collider for this collision pair
  ContactDetectionResult collisionResult; // All the contacts with this collider
  int collidingJacId = 0; // Id of the colliding actor's contact Jacobian for implicit contact
  int colliderJacId = 0; // Id of the collider actor's contact Jacobian for implicit contact

  // Clear the contact detection results. For performance reasons, the memory is not deallocated so
  // that it's reused across assemblies.
  void Clear() {
    collisionResult.Clear();
  }
};

// Orders active collisions by collider entity, then colliding partition ID.
struct ColliderPartitionLess {
  using Key = std::pair<entt::entity, int>;

  MOCHI_FORCE_INLINE static Key GetKey(ActiveCollision const& c) {
    return {c.colliderEntity, c.collisionResult.collidingPartitionId};
  }

  MOCHI_FORCE_INLINE bool operator()(ActiveCollision const& a, ActiveCollision const& b) const {
    return GetKey(a) < GetKey(b);
  }
};

/**
 * @brief Collider-partition contact results for one colliding actor.
 *
 * With one partition, this component contains one entry for every potential collider, including
 * pairs without contact. With multiple partitions, it contains only explicitly activated pairs;
 * inactive pair storage remains cached while its collider is a broad-phase candidate. Templatized
 * according to async or sync contact, and according to the time step (Current or StageStart).
 *
 * @note A collision-detection pass calls @ref SetUp and fills the results returned by
 * @ref GetNarrowPhaseResult. With multiple partitions, it activates contacting partitions with
 * @ref ActivatePartitionResult, then calls @ref FinalizeActiveCollisions before accessing active
 * partition results. It may then swap an aggregate result from @ref GetNarrowPhaseResult with the
 * collider's partition-zero result to avoid copying; the next @ref SetUp restores it.
 *
 * @note Entries are sorted by collider entity, then colliding partition ID, without duplicates,
 * after @ref SetUp and @ref FinalizeActiveCollisions. Activation may temporarily append unsorted
 * entries.
 *
 * @note Only @ref SetUp, @ref ActivatePartitionResult, and @ref FinalizeActiveCollisions add,
 * remove, or reorder entries. Callers may modify an entry's collision result and Jacobian IDs, but
 * never its collider entity or partition ID, which are the sort keys.
 */
template <bool kIsSync, TimeStep kTimeStep>
struct CActiveCollisions : private DynamicArray<ActiveCollision> {
 private:
  using Base = DynamicArray<ActiveCollision>;

 public:
  using Base::const_iterator;
  using Base::iterator;
  using Base::size_type;
  using Base::value_type;

  using Base::back;
  using Base::begin;
  using Base::data;
  using Base::empty;
  using Base::end;
  using Base::front;
  using Base::operator[];
  using Base::size;

  explicit CActiveCollisions(int numPartitions) : _numPartitions(numPartitions) {
    MOCHI_ASSERT_VERBOSE(numPartitions > 0, "Expected at least one contact partition.");
  }

  int GetNumPartitions() const {
    return _numPartitions;
  }

  // Whether any collider has contact points, rather than only potential contact.
  [[nodiscard]] bool HasContact() const {
    return std::any_of(
        begin(), end(), [](auto const& col) { return !col.collisionResult.Empty(); });
  }

  // Starts a collision-detection pass and invalidates references from the previous pass. Existing
  // pair and aggregate allocations are retained while their collider remains a potential collider.
  void SetUp(Span<entt::entity const> potentialColliders);

  // Activates a pair that is not already active, reusing its cached storage if available. The
  // returned reference is invalidated by later activation, finalization, or setup calls.
  ContactDetectionResult& ActivatePartitionResult(entt::entity colliderEntity, int partitionId);

  // Restores sorted order after activation. Earlier references may no longer identify the same
  // pair.
  void FinalizeActiveCollisions() {
    std::sort(begin(), end(), ColliderPartitionLess{});
    MOCHI_ASSERT_VERBOSE(IsSortedAndUnique(), "Duplicate active contact partition.");
  }

  // Requires sorted entries: after setup, or after finalization if pairs were activated.
  ContactDetectionResult& GetActivePartitionResult(entt::entity colliderEntity, int partitionId) {
    ColliderPartitionLess::Key const key{colliderEntity, partitionId};
    auto const it = std::lower_bound(
        begin(),
        end(),
        key,
        [](ActiveCollision const& collision, ColliderPartitionLess::Key const& k)
            MOCHI_FORCE_INLINE_LAMBDA { return ColliderPartitionLess::GetKey(collision) < k; });
    MOCHI_ASSERT_VERBOSE(
        it != end() && ColliderPartitionLess::GetKey(*it) == key,
        "Expected an active contact partition.");
    return it->collisionResult;
  }

  // Returns per-collider narrow-phase storage. In multi-partition mode, it must not be used after
  // being swapped with partition zero until the next setup call.
  ContactDetectionResult& GetNarrowPhaseResult(entt::entity colliderEntity) {
    if (_numPartitions == 1) {
      return GetActivePartitionResult(colliderEntity, 0);
    }

    auto const it = FindAggregate(colliderEntity);
    MOCHI_ASSERT_VERBOSE(
        it != _aggregateCollisions.end() && it->colliderEntity == colliderEntity,
        "Expected an aggregate result for the collider.");
    return it->collisionResult;
  }

 private:
  [[nodiscard]] bool IsSortedAndUnique() const {
    return std::adjacent_find(
               begin(), end(), [](ActiveCollision const& a, ActiveCollision const& b) {
                 return !ColliderPartitionLess{}(a, b);
               }) == end();
  }

  auto FindAggregate(entt::entity colliderEntity) {
    return std::lower_bound(
        _aggregateCollisions.begin(),
        _aggregateCollisions.end(),
        colliderEntity,
        [](ActiveCollision const& aggregate, entt::entity entity) {
          return aggregate.colliderEntity < entity;
        });
  }

  void RestoreAggregateResults();

  // Only used with multiple partitions. Unsorted.
  DynamicArray<ActiveCollision> _inactiveCollisions;
  // Only used with multiple partitions. One per potential collider, sorted by collider entity.
  DynamicArray<ActiveCollision> _aggregateCollisions;
  int _numPartitions;
};

} // namespace mochi
