/*
 * This file was @generated by mochi_gen_py. Do not modify this file by hand!!
 *
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// clang-format off

#pragma once

#include <mochi_core/utils/reflection.h>
#include <mochi_physics/mochi_physics_experimental.h>

#include <limits>

MOCHI_STRUCT_BEGIN_EX(mochi::experimental::DisplacementControlActuatorParams)
MOCHI_FIELD(targetDisplacement) MOCHI_ATTRIBUTE(NoSerializeDefaults)
MOCHI_FIELD(stiffness) MOCHI_ATTRIBUTE(NoSerializeDefaults)
MOCHI_FIELD(damping) MOCHI_ATTRIBUTE(NoSerializeDefaults)
MOCHI_FIELD(allowCompressiveForce) MOCHI_ATTRIBUTE(NoSerializeDefaults)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::experimental::RodMaterialParams)
MOCHI_FIELD(linearDensity) MOCHI_ATTRIBUTE(Units("kg/m"))
MOCHI_FIELD(linearRotationalInertia) MOCHI_ATTRIBUTE(Units("kg*m"))
MOCHI_FIELD(axialStiffness) MOCHI_ATTRIBUTE(Units("N"))
MOCHI_FIELD(torsionalStiffness) MOCHI_ATTRIBUTE(Units("N*m^2"))
MOCHI_FIELD(flexuralStiffness) MOCHI_ATTRIBUTE(Units("N*m^2"))
MOCHI_FIELD(massDampingCoefficient) MOCHI_ATTRIBUTE(Units("1/s"))
MOCHI_FIELD(stiffnessDampingCoefficient) MOCHI_ATTRIBUTE(Units("s"))
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::experimental::PointCloudColliderParams)
MOCHI_FIELD(radius) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_FIELD(selfContactExclusionRatio)
MOCHI_FIELD(spatialHashLoadFactor)
MOCHI_FIELD(selfContact)
MOCHI_FIELD(colliderTriangleElementType)
MOCHI_FIELD(colliderSegmentElementType)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::experimental::RodActorParams)
MOCHI_FIELD(name)
MOCHI_FIELD(layer)
MOCHI_FIELD(worldFromLocal)
MOCHI_FIELD(contact)
MOCHI_FIELD(contactElementType)
MOCHI_FIELD(material)
MOCHI_FIELD(colliderType)
MOCHI_FIELD(pointCloudCollider)
MOCHI_FIELD(hasGravity)
MOCHI_FIELD(useContactSkin)
MOCHI_FIELD(contactSkinElementType)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::experimental::ShellMaterialParams)
MOCHI_FIELD(membraneLambda) MOCHI_ATTRIBUTE(Units("Pa*m"))
MOCHI_FIELD(membraneMu) MOCHI_ATTRIBUTE(Units("Pa*m"))
MOCHI_FIELD(bendingAlpha) MOCHI_ATTRIBUTE(Units("Pa*m^3"))
MOCHI_FIELD(bendingBeta) MOCHI_ATTRIBUTE(Units("Pa*m^3"))
MOCHI_FIELD(density) MOCHI_ATTRIBUTE(Units("kg/m^2"))
MOCHI_FIELD(massDampingCoefficient) MOCHI_ATTRIBUTE(Units("1/s"))
MOCHI_FIELD(stiffnessDampingCoefficient) MOCHI_ATTRIBUTE(Units("s"))
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::experimental::ShellActorParams)
MOCHI_FIELD(name)
MOCHI_FIELD(layer)
MOCHI_FIELD(worldFromLocal)
MOCHI_FIELD(material)
MOCHI_FIELD(colliderType)
MOCHI_FIELD(contact)
MOCHI_FIELD(pointCloudCollider)
MOCHI_FIELD(hasGravity)
MOCHI_FIELD(contactElementType)
MOCHI_FIELD(useContactSkin)
MOCHI_STRUCT_END_EX()

// clang-format on
